apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weasel-backend
  name: weasel-backend
  namespace: weasel
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: weasel-backend
  template:
    metadata:
      labels:
        app: weasel-backend
    spec:
      serviceAccountName: weasel-eks-pod-sa
      containers:
      - image: 393035689023.dkr.ecr.us-east-1.amazonaws.com/weasel-backend:weasel-backend-102
        name: weasel-backend
        volumeMounts:
        - name: weasel-secrets
          mountPath: "/mnt/secrets"
          readOnly: true
        envFrom:
        - secretRef:
            name: weasel-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: weasel-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: weasel-secrets