apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weasel-backend-hpa
  namespace: weasel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weasel-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 60  # 메모리 사용률을 60%로 설정
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # CPU 사용률을 60%로 설정

